name = "hd2-loadout-manager"
compatibility_date = "2024-09-23"
pages_build_output_dir = "./public"

[[d1_databases]]
binding = "DB"
database_name = "hd2-loadout-manager"
database_id = "3a0219fb-604f-47d8-8ba8-f52b5f42ee3e"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "hd2-assets"
