-- ============================================================
-- Seed: Game Data from helldivers.wiki.gg
-- ============================================================

-- ------------------------------------------------------------
-- Stratagems
-- ------------------------------------------------------------
INSERT INTO stratagems (name, category, call_in_sequence, image_url) VALUES
  -- Support Weapons
  ('MG-43 Machine Gun', 'Support Weapon', 'down,left,down,up,right', '/api/assets/stratagems/mg-43-machine-gun.png'),
  ('EAT-17 Expendable Anti-Tank', 'Support Weapon', 'down,down,left,up,right', '/api/assets/stratagems/eat-17-expendable-anti-tank.png'),
  ('M-105 Stalwart', 'Support Weapon', 'down,left,down,up,up,left', '/api/assets/stratagems/m-105-stalwart.png'),
  ('LAS-98 Laser Cannon', 'Support Weapon', 'down,left,down,up,left', '/api/assets/stratagems/las-98-laser-cannon.png'),
  ('APW-1 Anti-Materiel Rifle', 'Support Weapon', 'down,left,right,up,down', '/api/assets/stratagems/apw-1-anti-materiel-rifle.png'),
  ('GL-21 Grenade Launcher', 'Support Weapon', 'down,left,up,left,down', '/api/assets/stratagems/gl-21-grenade-launcher.png'),
  ('GR-8 Recoilless Rifle', 'Support Weapon', 'down,left,right,right,left', '/api/assets/stratagems/gr-8-recoilless-rifle.png'),
  ('FLAM-40 Flamethrower', 'Support Weapon', 'down,left,up,down,up', '/api/assets/stratagems/flam-40-flamethrower.png'),
  ('MG-206 Heavy Machine Gun', 'Support Weapon', 'down,left,up,down,down', '/api/assets/stratagems/mg-206-heavy-machine-gun.png'),
  ('AC-8 Autocannon', 'Support Weapon', 'down,left,down,up,up,right', '/api/assets/stratagems/ac-8-autocannon.png'),
  ('ARC-3 Arc Thrower', 'Support Weapon', 'down,right,down,up,left,left', '/api/assets/stratagems/arc-3-arc-thrower.png'),
  ('LAS-99 Quasar Cannon', 'Support Weapon', 'down,down,up,left,right', '/api/assets/stratagems/las-99-quasar-cannon.png'),
  ('RL-77 Airburst Rocket Launcher', 'Support Weapon', 'down,up,up,left,right', '/api/assets/stratagems/rl-77-airburst-rocket-launcher.png'),
  ('MLS-4X Commando', 'Support Weapon', 'down,left,up,down,right', '/api/assets/stratagems/mls-4x-commando.png'),
  ('FAF-14 Spear', 'Support Weapon', 'down,down,up,down,down', '/api/assets/stratagems/faf-14-spear.png'),
  ('RS-422 Railgun', 'Support Weapon', 'down,right,down,up,left,right', '/api/assets/stratagems/rs-422-railgun.png'),
  ('StA-X3 W.A.S.P. Launcher', 'Support Weapon', 'down,down,up,down,right', '/api/assets/stratagems/sta-x3-w-a-s-p-launcher.png'),
  ('CQC-20 Breaching Hammer', 'Support Weapon', 'down,left,right,left,up', '/api/assets/stratagems/cqc-20-breaching-hammer.png'),
  ('PLAS-45 Epoch', 'Support Weapon', 'down,left,up,left,right', '/api/assets/stratagems/plas-45-epoch.png'),
  ('MGX-42 Bullet Storm', 'Support Weapon', 'down,left,down,right,up,left', '/api/assets/stratagems/mgx-42-bullet-storm.png'),
  ('S-11 Speargun', 'Support Weapon', 'down,right,down,left,up,right', '/api/assets/stratagems/s-11-speargun.png'),
  ('CQC-9 Defoliation Tool', 'Support Weapon', 'down,left,right,right,down', '/api/assets/stratagems/cqc-9-defoliation-tool.png'),
  ('TX-41 Sterilizer', 'Support Weapon', 'down,left,up,down,left', '/api/assets/stratagems/tx-41-sterilizer.png'),
  ('EAT-700 Expendable Napalm', 'Support Weapon', 'down,down,left,up,left', '/api/assets/stratagems/eat-700-expendable-napalm.png'),
  ('EAT-411 Leveller', 'Support Weapon', 'down,down,left,up,down', '/api/assets/stratagems/eat-411-leveller.png'),
  ('GL-52 De-Escalator', 'Support Weapon', 'down,right,up,left,right', '/api/assets/stratagems/gl-52-de-escalator.png'),
  ('GL-28 Belt-Fed Grenade Launcher', 'Support Weapon', 'down,left,up,left,up,up', '/api/assets/stratagems/gl-28-belt-fed-grenade-launcher.png'),
  ('B/MD C4 Pack', 'Support Weapon', 'down,right,up,up,right,up', '/api/assets/stratagems/b-md-c4-pack.png'),
  ('MS-11 Solo Silo', 'Support Weapon', 'down,up,right,down,down', '/api/assets/stratagems/ms-11-solo-silo.png'),
  ('B/FLAM-80 Cremator', 'Support Weapon', 'down,down,right,down,up,up', '/api/assets/stratagems/b-flam-80-cremator.png'),
  ('M-1000 Maxigun', 'Support Weapon', 'down,left,right,down,up,up', '/api/assets/stratagems/m-1000-maxigun.png'),
  ('CQC-1 One True Flag', 'Support Weapon', 'down,left,right,right,up', '/api/assets/stratagems/cqc-1-one-true-flag.png'),
  -- Orbital
  ('Orbital Precision Strike', 'Orbital', 'right,right,up', '/api/assets/stratagems/orbital-precision-strike.png'),
  ('Orbital Gatling Barrage', 'Orbital', 'right,down,left,up,up', '/api/assets/stratagems/orbital-gatling-barrage.png'),
  ('Orbital Gas Strike', 'Orbital', 'right,right,down,right', '/api/assets/stratagems/orbital-gas-strike.png'),
  ('Orbital 120mm HE Barrage', 'Orbital', 'right,right,down,left,right,down', '/api/assets/stratagems/orbital-120mm-he-barrage.png'),
  ('Orbital Airburst Strike', 'Orbital', 'right,right,right', '/api/assets/stratagems/orbital-airburst-strike.png'),
  ('Orbital Smoke Strike', 'Orbital', 'right,right,down,up', '/api/assets/stratagems/orbital-smoke-strike.png'),
  ('Orbital EMS Strike', 'Orbital', 'right,right,left,down', '/api/assets/stratagems/orbital-ems-strike.png'),
  ('Orbital 380mm HE Barrage', 'Orbital', 'right,down,up,up,left,down,down', '/api/assets/stratagems/orbital-380mm-he-barrage.png'),
  ('Orbital Walking Barrage', 'Orbital', 'right,down,right,down,right,down', '/api/assets/stratagems/orbital-walking-barrage.png'),
  ('Orbital Laser', 'Orbital', 'right,down,up,right,down', '/api/assets/stratagems/orbital-laser.png'),
  ('Orbital Napalm Barrage', 'Orbital', 'right,right,down,left,right,up', '/api/assets/stratagems/orbital-napalm-barrage.png'),
  ('Orbital Railcannon Strike', 'Orbital', 'right,up,down,down,right', '/api/assets/stratagems/orbital-railcannon-strike.png'),
  ('Orbital Illumination Flare', 'Orbital', 'right,right,left,left', '/api/assets/stratagems/orbital-illumination-flare.png'),
  -- Eagle
  ('Eagle Strafing Run', 'Eagle', 'up,right,right', '/api/assets/stratagems/eagle-strafing-run.png'),
  ('Eagle Airstrike', 'Eagle', 'up,right,down,right', '/api/assets/stratagems/eagle-airstrike.png'),
  ('Eagle Cluster Bomb', 'Eagle', 'up,right,down,down,right', '/api/assets/stratagems/eagle-cluster-bomb.png'),
  ('Eagle Smoke Strike', 'Eagle', 'up,right,up,down', '/api/assets/stratagems/eagle-smoke-strike.png'),
  ('Eagle Napalm Airstrike', 'Eagle', 'up,right,down,up', '/api/assets/stratagems/eagle-napalm-airstrike.png'),
  ('Eagle 110mm Rocket Pods', 'Eagle', 'up,right,up,left', '/api/assets/stratagems/eagle-110mm-rocket-pods.png'),
  ('Eagle 500kg Bomb', 'Eagle', 'up,right,down,down,down', '/api/assets/stratagems/eagle-500kg-bomb.png'),
  -- Emplacements / Defense
  ('MD-6 Anti-Personnel Minefield', 'Defense', 'down,left,up,right', '/api/assets/stratagems/md-6-anti-personnel-minefield.png'),
  ('MD-I4 Incendiary Mines', 'Defense', 'down,left,left,down', '/api/assets/stratagems/md-i4-incendiary-mines.png'),
  ('MD-17 Anti-Tank Mines', 'Defense', 'down,left,up,up', '/api/assets/stratagems/md-17-anti-tank-mines.png'),
  ('FX-12 Shield Generator Relay', 'Defense', 'down,down,left,right,left,right', '/api/assets/stratagems/fx-12-shield-generator-relay.png'),
  ('E/MG-101 HMG Emplacement', 'Defense', 'down,up,left,right,right,left', '/api/assets/stratagems/e-mg-101-hmg-emplacement.png'),
  ('E/GL-21 Grenadier Battlement', 'Defense', 'down,right,down,left,right', '/api/assets/stratagems/e-gl-21-grenadier-battlement.png'),
  ('MD-8 Gas Mines', 'Defense', 'down,left,left,right', '/api/assets/stratagems/md-8-gas-mines.png'),
  ('E/AT-12 Anti-Tank Emplacement', 'Defense', 'down,up,left,right,right,right', '/api/assets/stratagems/e-at-12-anti-tank-emplacement.png'),
  -- Sentries
  ('A/MG-43 Machine Gun Sentry', 'Defense', 'down,up,right,right,up', '/api/assets/stratagems/a-mg-43-machine-gun-sentry.png'),
  ('A/G-16 Gatling Sentry', 'Defense', 'down,up,right,left', '/api/assets/stratagems/a-g-16-gatling-sentry.png'),
  ('A/AC-8 Autocannon Sentry', 'Defense', 'down,up,right,up,left,up', '/api/assets/stratagems/a-ac-8-autocannon-sentry.png'),
  ('A/M-12 Mortar Sentry', 'Defense', 'down,up,right,right,down', '/api/assets/stratagems/a-m-12-mortar-sentry.png'),
  ('A/MLS-4X Rocket Sentry', 'Defense', 'down,up,right,right,left', '/api/assets/stratagems/a-mls-4x-rocket-sentry.png'),
  ('A/ARC-3 Tesla Tower', 'Defense', 'down,up,right,up,left,right', '/api/assets/stratagems/a-arc-3-tesla-tower.png'),
  ('A/M-23 EMS Mortar Sentry', 'Defense', 'down,up,right,down,right', '/api/assets/stratagems/a-m-23-ems-mortar-sentry.png'),
  ('A/LAS-98 Laser Sentry', 'Defense', 'down,up,right,down,up,right', '/api/assets/stratagems/a-las-98-laser-sentry.png'),
  ('A/FLAM-40 Flame Sentry', 'Defense', 'down,up,right,down,up,up', '/api/assets/stratagems/a-flam-40-flame-sentry.png'),
  ('A/GM-17 Gas Mortar Sentry', 'Defense', 'down,up,right,down,left', '/api/assets/stratagems/a-gm-17-gas-mortar-sentry.png'),
  -- Backpacks
  ('B-1 Supply Pack', 'Backpack', 'down,left,down,up,up,down', '/api/assets/stratagems/b-1-supply-pack.png'),
  ('LIFT-850 Jump Pack', 'Backpack', 'down,up,up,down,up', '/api/assets/stratagems/lift-850-jump-pack.png'),
  ('SH-20 Ballistic Shield Backpack', 'Backpack', 'down,left,down,down,up,left', '/api/assets/stratagems/sh-20-ballistic-shield-backpack.png'),
  ('AX/AR-23 Guard Dog', 'Backpack', 'down,up,left,up,right,down', '/api/assets/stratagems/ax-ar-23-guard-dog.png'),
  ('AX/LAS-5 Rover', 'Backpack', 'down,up,left,up,right,right', '/api/assets/stratagems/ax-las-5-rover.png'),
  ('SH-32 Shield Generator Pack', 'Backpack', 'down,up,left,right,left,right', '/api/assets/stratagems/sh-32-shield-generator-pack.png'),
  ('SH-51 Directional Shield', 'Backpack', 'down,up,left,right,up,up', '/api/assets/stratagems/sh-51-directional-shield.png'),
  ('AX/FLAM-75 Hot Dog', 'Backpack', 'down,up,left,up,left,left', '/api/assets/stratagems/ax-flam-75-hot-dog.png'),
  ('B-100 Portable Hellbomb', 'Backpack', 'down,right,up,up,up', '/api/assets/stratagems/b-100-portable-hellbomb.png'),
  ('AX/ARC-3 K-9', 'Backpack', 'down,up,left,up,right,left', '/api/assets/stratagems/ax-arc-3-k-9.png'),
  ('LIFT-860 Hover Pack', 'Backpack', 'down,up,up,down,left,right', '/api/assets/stratagems/lift-860-hover-pack.png'),
  ('AX/TX-13 Dog Breath', 'Backpack', 'down,up,left,up,right,up', '/api/assets/stratagems/ax-tx-13-dog-breath.png'),
  ('LIFT-182 Warp Pack', 'Backpack', 'down,left,right,down,left,right', '/api/assets/stratagems/lift-182-warp-pack.png'),
  -- Vehicles
  ('EXO-45 Patriot Exosuit', 'Mission', 'left,down,right,up,left,down,down', '/api/assets/stratagems/exo-45-patriot-exosuit.png'),
  ('EXO-49 Emancipator Exosuit', 'Mission', 'left,down,right,up,left,down,up', '/api/assets/stratagems/exo-49-emancipator-exosuit.png'),
  ('M-102 Fast Recon Vehicle', 'Mission', 'left,down,right,down,right,down,up', '/api/assets/stratagems/m-102-fast-recon-vehicle.png'),
  ('TD-220 Bastion MK XVI', 'Mission', 'left,down,right,down,left,down,up,down,up', '/api/assets/stratagems/td-220-bastion-mk-xvi.png'),
  ('EXO-55 Breakthrough Exosuit', 'Mission', 'left,down,right,left,right,down,up', '/api/assets/stratagems/exo-55-breakthrough-exosuit.png'),
  ('EXO-51 Lumberer Exosuit', 'Mission', 'left,down,right,up,right,left,up', '/api/assets/stratagems/exo-51-lumberer-exosuit.png'),
  -- Mission - Ship
  ('Reinforce', 'Mission', 'up,down,right,left,up', '/api/assets/stratagems/reinforce.png'),
  ('Resupply', 'Mission', 'down,down,up,right', '/api/assets/stratagems/resupply.png'),
  ('SoS Beacon', 'Mission', 'up,down,right,up', '/api/assets/stratagems/sos-beacon.png'),
  ('Eagle Rearm', 'Mission', 'up,up,left,up,right', '/api/assets/stratagems/eagle-rearm.png'),
  ('Call In Super Destroyer', 'Mission', 'up,up,down,down,left,right,left,right', '/api/assets/stratagems/call-in-super-destroyer.png'),
  -- Mission - Objective
  ('NUX-223 Hellbomb', 'Mission', 'down,up,left,down,up,right,down,up', '/api/assets/stratagems/nux-223-hellbomb.png'),
  ('Upload Data', 'Mission', 'left,right,up,up,up', '/api/assets/stratagems/upload-data.png'),
  ('SSSD Delivery', 'Mission', 'down,down,down,down,down,up,up', '/api/assets/stratagems/sssd-delivery.png'),
  ('Super Earth Flag', 'Mission', 'down,up,down,up', '/api/assets/stratagems/super-earth-flag.png'),
  ('Seismic Probe', 'Mission', 'up,up,left,right,down,down', '/api/assets/stratagems/seismic-probe.png'),
  ('Prospecting Drill', 'Mission', 'down,down,left,right,down,down', '/api/assets/stratagems/prospecting-drill.png'),
  ('Dark Fluid Vessel', 'Mission', 'up,left,right,down,up,up', '/api/assets/stratagems/dark-fluid-vessel.png'),
  ('Tectonic Drill', 'Mission', 'up,down,up,down,up,down', '/api/assets/stratagems/tectonic-drill.png'),
  ('Hive Breaker Drill', 'Mission', 'left,up,down,right,down,down', '/api/assets/stratagems/hive-breaker-drill.png'),
  ('Cargo Container', 'Mission', 'up,up,down,down,right,down', '/api/assets/stratagems/cargo-container.png'),
  ('Reinforcement Pods', 'Mission', 'left,right,up,up,up', '/api/assets/stratagems/reinforcement-pods.png'),
  ('SEAF Artillery', 'Mission', 'right,up,up,down', '/api/assets/stratagems/seaf-artillery.png');

-- ------------------------------------------------------------
-- Primary Weapons
-- ------------------------------------------------------------
INSERT INTO weapons_primary (name, type, image_url) VALUES
  -- Assault Rifles
  ('AR-23 Liberator', 'Assault Rifle', '/api/assets/weapons/primary/ar-23-liberator.png'),
  ('AR-23P Liberator Penetrator', 'Assault Rifle', '/api/assets/weapons/primary/ar-23p-liberator-penetrator.png'),
  ('AR-23C Liberator Concussive', 'Assault Rifle', '/api/assets/weapons/primary/ar-23c-liberator-concussive.png'),
  ('StA-52 Assault Rifle', 'Assault Rifle', '/api/assets/weapons/primary/sta-52-assault-rifle.png'),
  ('AR-32 Pacifier', 'Assault Rifle', '/api/assets/weapons/primary/ar-32-pacifier.png'),
  ('AR-2 Coyote', 'Assault Rifle', '/api/assets/weapons/primary/ar-2-coyote.png'),
  ('MA5C Assault Rifle', 'Assault Rifle', '/api/assets/weapons/primary/ma5c-assault-rifle.png'),
  ('AR-23A Liberator Carbine', 'Assault Rifle', '/api/assets/weapons/primary/ar-23a-liberator-carbine.png'),
  ('AR-61 Tenderizer', 'Assault Rifle', '/api/assets/weapons/primary/ar-61-tenderizer.png'),
  ('BR-14 Adjudicator', 'Assault Rifle', '/api/assets/weapons/primary/br-14-adjudicator.png'),
  ('AR/GL-21 One-Two', 'Assault Rifle', '/api/assets/weapons/primary/ar-gl-21-one-two.png'),
  ('AR-59 Suppressor', 'Assault Rifle', '/api/assets/weapons/primary/ar-59-suppressor.png'),
  -- Marksman Rifles
  ('R-2 Amendment', 'Marksman Rifle', '/api/assets/weapons/primary/r-2-amendment.png'),
  ('R-2124 Constitution', 'Marksman Rifle', '/api/assets/weapons/primary/r-2124-constitution.png'),
  ('R-6 Deadeye', 'Marksman Rifle', '/api/assets/weapons/primary/r-6-deadeye.png'),
  ('R-63 Diligence', 'Marksman Rifle', '/api/assets/weapons/primary/r-63-diligence.png'),
  ('R-63CS Diligence Counter Sniper', 'Marksman Rifle', '/api/assets/weapons/primary/r-63cs-diligence-counter-sniper.png'),
  ('R-72 Censor', 'Marksman Rifle', '/api/assets/weapons/primary/r-72-censor.png'),
  -- Submachine Guns
  ('MP-98 Knight', 'Submachine Gun', '/api/assets/weapons/primary/mp-98-knight.png'),
  ('StA-11 SMG', 'Submachine Gun', '/api/assets/weapons/primary/sta-11-smg.png'),
  ('M7S SMG', 'Submachine Gun', '/api/assets/weapons/primary/m7s-smg.png'),
  ('SMG-32 Reprimand', 'Submachine Gun', '/api/assets/weapons/primary/smg-32-reprimand.png'),
  ('SMG-37 Defender', 'Submachine Gun', '/api/assets/weapons/primary/smg-37-defender.png'),
  ('SMG-72 Pummeler', 'Submachine Gun', '/api/assets/weapons/primary/smg-72-pummeler.png'),
  ('SMG/FLAM-34 Stoker', 'Submachine Gun', '/api/assets/weapons/primary/smg-flam-34-stoker.png'),
  ('SMG-203 Gallant', 'Submachine Gun', '/api/assets/weapons/primary/smg-203-gallant.png'),
  -- Shotguns
  ('SG-8 Punisher', 'Shotgun', '/api/assets/weapons/primary/sg-8-punisher.png'),
  ('SG-8S Slugger', 'Shotgun', '/api/assets/weapons/primary/sg-8s-slugger.png'),
  ('SG-20 Halt', 'Shotgun', '/api/assets/weapons/primary/sg-20-halt.png'),
  ('SG-451 Cookout', 'Shotgun', '/api/assets/weapons/primary/sg-451-cookout.png'),
  ('DBS-2 Double Freedom', 'Shotgun', '/api/assets/weapons/primary/dbs-2-double-freedom.png'),
  ('M90A Shotgun', 'Shotgun', '/api/assets/weapons/primary/m90a-shotgun.png'),
  ('SG-225 Breaker', 'Shotgun', '/api/assets/weapons/primary/sg-225-breaker.png'),
  ('SG-225SP Breaker Spray&Pray', 'Shotgun', '/api/assets/weapons/primary/sg-225sp-breaker-spray-pray.png'),
  ('SG-225IE Breaker Incendiary', 'Shotgun', '/api/assets/weapons/primary/sg-225ie-breaker-incendiary.png'),
  ('SG-97 Sweeper', 'Shotgun', '/api/assets/weapons/primary/sg-97-sweeper.png'),
  -- Explosive
  ('CB-9 Exploding Crossbow', 'Explosive', '/api/assets/weapons/primary/cb-9-exploding-crossbow.png'),
  ('R-36 Eruptor', 'Explosive', '/api/assets/weapons/primary/r-36-eruptor.png'),
  -- Energy-Based
  ('SG-8P Punisher Plasma', 'Energy', '/api/assets/weapons/primary/sg-8p-punisher-plasma.png'),
  ('PLAS-39 Accelerator Rifle', 'Energy', '/api/assets/weapons/primary/plas-39-accelerator-rifle.png'),
  ('ARC-12 Blitzer', 'Energy', '/api/assets/weapons/primary/arc-12-blitzer.png'),
  ('LAS-5 Scythe', 'Energy', '/api/assets/weapons/primary/las-5-scythe.png'),
  ('LAS-16 Sickle', 'Energy', '/api/assets/weapons/primary/las-16-sickle.png'),
  ('LAS-17 Double-Edge Sickle', 'Energy', '/api/assets/weapons/primary/las-17-double-edge-sickle.png'),
  ('PLAS-1 Scorcher', 'Energy', '/api/assets/weapons/primary/plas-1-scorcher.png'),
  ('PLAS-101 Purifier', 'Energy', '/api/assets/weapons/primary/plas-101-purifier.png'),
  ('LAS-13 Trident', 'Energy', '/api/assets/weapons/primary/las-13-trident.png'),
  -- Special
  ('VG-70 Variable', 'Special', '/api/assets/weapons/primary/vg-70-variable.png'),
  ('FLAM-66 Torcher', 'Special', '/api/assets/weapons/primary/flam-66-torcher.png'),
  ('JAR-5 Dominator', 'Special', '/api/assets/weapons/primary/jar-5-dominator.png');

-- ------------------------------------------------------------
-- Secondary Weapons
-- ------------------------------------------------------------
INSERT INTO weapons_secondary (name, image_url) VALUES
  -- Pistols
  ('P-92 Warrant', '/api/assets/weapons/secondary/p-92-warrant.png'),
  ('P-2 Peacemaker', '/api/assets/weapons/secondary/p-2-peacemaker.png'),
  ('P-19 Redeemer', '/api/assets/weapons/secondary/p-19-redeemer.png'),
  ('P-113 Verdict', '/api/assets/weapons/secondary/p-113-verdict.png'),
  ('M6C/SOCOM Pistol', '/api/assets/weapons/secondary/m6c-socom-pistol.png'),
  ('P-4 Senator', '/api/assets/weapons/secondary/p-4-senator.png'),
  ('P-69 Veto', '/api/assets/weapons/secondary/p-69-veto.png'),
  -- Melee
  ('CQC-19 Stun Lance', '/api/assets/weapons/secondary/cqc-19-stun-lance.png'),
  ('CQC-2 Saber', '/api/assets/weapons/secondary/cqc-2-saber.png'),
  ('CQC-30 Stun Baton', '/api/assets/weapons/secondary/cqc-30-stun-baton.png'),
  ('CQC-5 Combat Hatchet', '/api/assets/weapons/secondary/cqc-5-combat-hatchet.png'),
  ('CQC-73 Entrenchment Tool', '/api/assets/weapons/secondary/cqc-73-entrenchment-tool.png'),
  ('CQC-42 Machete', '/api/assets/weapons/secondary/cqc-42-machete.png'),
  -- Special
  ('P-11 Stim Pistol', '/api/assets/weapons/secondary/p-11-stim-pistol.png'),
  ('SG-22 Bushwhacker', '/api/assets/weapons/secondary/sg-22-bushwhacker.png'),
  ('LAS-58 Talon', '/api/assets/weapons/secondary/las-58-talon.png'),
  ('P-72 Crisper', '/api/assets/weapons/secondary/p-72-crisper.png'),
  ('GP-31 Grenade Pistol', '/api/assets/weapons/secondary/gp-31-grenade-pistol.png'),
  ('LAS-7 Dagger', '/api/assets/weapons/secondary/las-7-dagger.png'),
  ('GP-20 Ultimatum', '/api/assets/weapons/secondary/gp-20-ultimatum.png'),
  ('PLAS-15 Loyalist', '/api/assets/weapons/secondary/plas-15-loyalist.png'),
  ('P-35 Re-Educator', '/api/assets/weapons/secondary/p-35-re-educator.png'),
  ('P-33 Missile Pistol', '/api/assets/weapons/secondary/p-33-missile-pistol.png');

-- ------------------------------------------------------------
-- Grenades
-- ------------------------------------------------------------
INSERT INTO grenades (name, image_url) VALUES
  ('TED-63 Dynamite', '/api/assets/grenades/ted-63-dynamite.png'),
  ('G-6 Frag', '/api/assets/grenades/g-6-frag.png'),
  ('G-12 High Explosive', '/api/assets/grenades/g-12-high-explosive.png'),
  ('G-10 Incendiary', '/api/assets/grenades/g-10-incendiary.png'),
  ('G-7 Pineapple', '/api/assets/grenades/g-7-pineapple.png'),
  ('G-16 Impact', '/api/assets/grenades/g-16-impact.png'),
  ('G-13 Incendiary Impact', '/api/assets/grenades/g-13-incendiary-impact.png'),
  ('G-23 Stun', '/api/assets/grenades/g-23-stun.png'),
  ('G-4 Gas', '/api/assets/grenades/g-4-gas.png'),
  ('G-50 Seeker', '/api/assets/grenades/g-50-seeker.png'),
  ('G-3 Smoke', '/api/assets/grenades/g-3-smoke.png'),
  ('G-123 Thermite', '/api/assets/grenades/g-123-thermite.png'),
  ('K-2 Throwing Knife', '/api/assets/grenades/k-2-throwing-knife.png'),
  ('G-142 Pyrotech', '/api/assets/grenades/g-142-pyrotech.png'),
  ('G-109 Urchin', '/api/assets/grenades/g-109-urchin.png'),
  ('G-31 Arc', '/api/assets/grenades/g-31-arc.png'),
  ('TM-1 Lure Mine', '/api/assets/grenades/tm-1-lure-mine.png'),
  ('G-89 Smokescreen', '/api/assets/grenades/g-89-smokescreen.png'),
  ('G/SH-39 Shield', '/api/assets/grenades/g-sh-39-shield.png'),
  ('G-48 Giga Grenade', '/api/assets/grenades/g-48-giga-grenade.png');

-- ------------------------------------------------------------
-- Armor
-- ------------------------------------------------------------
INSERT INTO armor (name, armor_class, passive, image_url) VALUES
  -- Light Armor
  ('SC-37 Legionnaire', 'light', 'Servo-Assisted', '/api/assets/armor/sc-37-legionnaire.png'),
  ('SC-34 Infiltrator', 'light', 'Scout', '/api/assets/armor/sc-34-infiltrator.png'),
  ('SC-30 Trailblazer Scout', 'light', 'Scout', '/api/assets/armor/sc-30-trailblazer-scout.png'),
  ('CE-74 Breaker', 'light', 'Engineering Kit', '/api/assets/armor/ce-74-breaker.png'),
  ('FS-38 Eradicator', 'light', 'Fortified', '/api/assets/armor/fs-38-eradicator.png'),
  ('B-08 Light Gunner', 'light', 'Extra Padding', '/api/assets/armor/b-08-light-gunner.png'),
  ('CM-21 Trench Paramedic', 'light', 'Med-Kit', '/api/assets/armor/cm-21-trench-paramedic.png'),
  ('CE-67 Titan', 'light', 'Engineering Kit', '/api/assets/armor/ce-67-titan.png'),
  ('EX-00 Prototype X', 'light', 'Electrical Conduit', '/api/assets/armor/ex-00-prototype-x.png'),
  ('CE-07 Demolition Specialist', 'light', 'Engineering Kit', '/api/assets/armor/ce-07-demolition-specialist.png'),
  ('FS-37 Ravager', 'light', 'Engineering Kit', '/api/assets/armor/fs-37-ravager.png'),
  ('CW-4 Arctic Ranger', 'light', 'Scout', '/api/assets/armor/cw-4-arctic-ranger.png'),
  ('PH-9 Predator', 'light', 'Peak Physique', '/api/assets/armor/ph-9-predator.png'),
  ('I-09 Heatseeker', 'light', 'Inflammable', '/api/assets/armor/i-09-heatseeker.png'),
  ('AF-50 Noxious Ranger', 'light', 'Advanced Filtration', '/api/assets/armor/af-50-noxious-ranger.png'),
  ('UF-16 Inspector', 'light', 'Unflinching', '/api/assets/armor/uf-16-inspector.png'),
  ('SR-24 Street Scout', 'light', 'Siege-Ready', '/api/assets/armor/sr-24-street-scout.png'),
  ('AC-2 Obedient', 'light', 'Acclimated', '/api/assets/armor/ac-2-obedient.png'),
  ('IE-57 Hell-Bent', 'light', 'Integrated Explosives', '/api/assets/armor/ie-57-hell-bent.png'),
  ('GS-11 Democracy''s Deputy', 'light', 'Gunslinger', '/api/assets/armor/gs-11-democracy-s-deputy.png'),
  ('RE-1861 Parade Commander', 'light', 'Reinforced Epaulettes', '/api/assets/armor/re-1861-parade-commander.png'),
  ('BP-32 Jackboot', 'light', 'Ballistic Padding', '/api/assets/armor/bp-32-jackboot.png'),
  ('AD-11 Livewire', 'light', 'Adreno-Defibrillator', '/api/assets/armor/ad-11-livewire.png'),
  ('DS-10 Big Game Hunter', 'light', 'Desert Stormer', '/api/assets/armor/ds-10-big-game-hunter.png'),
  ('RS-20 Constrictor', 'light', 'Rock Solid', '/api/assets/armor/rs-20-constrictor.png'),
  ('RS-100 Sanctioner', 'light', 'Reduced Signature', '/api/assets/armor/rs-100-sanctioner.png'),
  ('RS-89 Shadow Paragon', 'light', 'Reduced Signature', '/api/assets/armor/rs-89-shadow-paragon.png'),
  ('CPH-26 Commandant', 'light', 'Concussive Padding', '/api/assets/armor/cph-26-commandant.png'),
  ('O-3 Free Spirit', 'light', 'Oxygenator', '/api/assets/armor/o-3-free-spirit.png'),
  -- Medium Armor
  ('B-01 Tactical', 'medium', 'Extra Padding', '/api/assets/armor/b-01-tactical.png'),
  ('TR-7 Ambassador of the Brand', 'medium', 'Extra Padding', '/api/assets/armor/tr-7-ambassador-of-the-brand.png'),
  ('TR-9 Cavalier of Democracy', 'medium', 'Democracy Protects', '/api/assets/armor/tr-9-cavalier-of-democracy.png'),
  ('DP-53 Savior of the Free', 'medium', 'Democracy Protects', '/api/assets/armor/dp-53-savior-of-the-free.png'),
  ('TR-117 Alpha Commander', 'medium', 'Med-Kit', '/api/assets/armor/tr-117-alpha-commander.png'),
  ('SC-15 Drone Master', 'medium', 'Engineering Kit', '/api/assets/armor/sc-15-drone-master.png'),
  ('CE-35 Trench Engineer', 'medium', 'Engineering Kit', '/api/assets/armor/ce-35-trench-engineer.png'),
  ('CM-09 Bonesnapper', 'medium', 'Med-Kit', '/api/assets/armor/cm-09-bonesnapper.png'),
  ('DP-40 Hero of the Federation', 'medium', 'Democracy Protects', '/api/assets/armor/dp-40-hero-of-the-federation.png'),
  ('SA-04 Combat Technician', 'medium', 'Scout', '/api/assets/armor/sa-04-combat-technician.png'),
  ('CM-14 Physician', 'medium', 'Med-Kit', '/api/assets/armor/cm-14-physician.png'),
  ('DP-11 Champion of the People', 'medium', 'Democracy Protects', '/api/assets/armor/dp-11-champion-of-the-people.png'),
  ('SA-25 Steel Trooper', 'medium', 'Servo-Assisted', '/api/assets/armor/sa-25-steel-trooper.png'),
  ('SA-12 Servo Assisted', 'medium', 'Servo-Assisted', '/api/assets/armor/sa-12-servo-assisted.png'),
  ('B-24 Enforcer', 'medium', 'Fortified', '/api/assets/armor/b-24-enforcer.png'),
  ('CE-81 Juggernaut', 'medium', 'Engineering Kit', '/api/assets/armor/ce-81-juggernaut.png'),
  ('FS-34 Exterminator', 'medium', 'Fortified', '/api/assets/armor/fs-34-exterminator.png'),
  ('EX-03 Prototype 3', 'medium', 'Electrical Conduit', '/api/assets/armor/ex-03-prototype-3.png'),
  ('EX-16 Prototype 16', 'medium', 'Electrical Conduit', '/api/assets/armor/ex-16-prototype-16.png'),
  ('CE-27 Ground Breaker', 'medium', 'Engineering Kit', '/api/assets/armor/ce-27-ground-breaker.png'),
  ('CM-10 Clinician', 'medium', 'Med-Kit', '/api/assets/armor/cm-10-clinician.png'),
  ('CW-9 White Wolf', 'medium', 'Extra Padding', '/api/assets/armor/cw-9-white-wolf.png'),
  ('PH-56 Jaguar', 'medium', 'Peak Physique', '/api/assets/armor/ph-56-jaguar.png'),
  ('TR-40 Gold Eagle', 'medium', 'Extra Padding', '/api/assets/armor/tr-40-gold-eagle.png'),
  ('I-92 Fire Fighter', 'medium', 'Inflammable', '/api/assets/armor/i-92-fire-fighter.png'),
  ('I-102 Draconaught', 'medium', 'Inflammable', '/api/assets/armor/i-102-draconaught.png'),
  ('AF-91 Field Chemist', 'medium', 'Advanced Filtration', '/api/assets/armor/af-91-field-chemist.png'),
  ('AF-02 Haz-Master', 'medium', 'Advanced Filtration', '/api/assets/armor/af-02-haz-master.png'),
  ('DP-00 Tactical', 'medium', 'Democracy Protects', '/api/assets/armor/dp-00-tactical.png'),
  ('UF-84 Doubt Killer', 'medium', 'Unflinching', '/api/assets/armor/uf-84-doubt-killer.png'),
  ('UF-50 Bloodhound', 'medium', 'Unflinching', '/api/assets/armor/uf-50-bloodhound.png'),
  ('AC-1 Dutiful', 'medium', 'Acclimated', '/api/assets/armor/ac-1-dutiful.png'),
  ('IE-3 Martyr', 'medium', 'Integrated Explosives', '/api/assets/armor/ie-3-martyr.png'),
  ('IE-12 Righteous', 'medium', 'Integrated Explosives', '/api/assets/armor/ie-12-righteous.png'),
  ('B-22 Model Citizen', 'medium', 'Democracy Protects', '/api/assets/armor/b-22-model-citizen.png'),
  ('GS-17 Frontier Marshal', 'medium', 'Gunslinger', '/api/assets/armor/gs-17-frontier-marshal.png'),
  ('RE-2310 Honorary Guard', 'medium', 'Reinforced Epaulettes', '/api/assets/armor/re-2310-honorary-guard.png'),
  ('BP-20 Correct Officer', 'medium', 'Ballistic Padding', '/api/assets/armor/bp-20-correct-officer.png'),
  ('AD-26 Bleeding Edge', 'medium', 'Adreno-Defibrillator', '/api/assets/armor/ad-26-bleeding-edge.png'),
  ('A-9 Helljumper', 'medium', 'Feet First', '/api/assets/armor/a-9-helljumper.png'),
  ('A-35 Recon', 'medium', 'Feet First', '/api/assets/armor/a-35-recon.png'),
  ('DS-191 Scorpion', 'medium', 'Desert Stormer', '/api/assets/armor/ds-191-scorpion.png'),
  ('RS-6 Fiend Destroyer', 'medium', 'Rock Solid', '/api/assets/armor/rs-6-fiend-destroyer.png'),
  ('RS-67 Null Cipher', 'medium', 'Reduced Signature', '/api/assets/armor/rs-67-null-cipher.png'),
  ('SA-7 Headfirst', 'medium', 'Supplementary Adrenaline', '/api/assets/armor/sa-7-headfirst.png'),
  ('DP-8 Mountain-Scaled', 'medium', 'Siege-Ready', '/api/assets/armor/dp-8-mountain-scaled.png'),
  ('CPG-48 Sapper', 'medium', 'Concussive Padding', '/api/assets/armor/cpg-48-sapper.png'),
  ('O-44 Bonded Pilot', 'medium', 'Oxygenator', '/api/assets/armor/o-44-bonded-pilot.png'),
  -- Heavy Armor
  ('CW-22 Kodiak', 'heavy', 'Fortified', '/api/assets/armor/cw-22-kodiak.png'),
  ('TR-62 Knight', 'heavy', 'Servo-Assisted', '/api/assets/armor/tr-62-knight.png'),
  ('FS-05 Marksman', 'heavy', 'Fortified', '/api/assets/armor/fs-05-marksman.png'),
  ('FS-23 Battle Master', 'heavy', 'Fortified', '/api/assets/armor/fs-23-battle-master.png'),
  ('SA-32 Dynamo', 'heavy', 'Servo-Assisted', '/api/assets/armor/sa-32-dynamo.png'),
  ('B-27 Fortified Commando', 'heavy', 'Extra Padding', '/api/assets/armor/b-27-fortified-commando.png'),
  ('FS-61 Dreadnought', 'heavy', 'Servo-Assisted', '/api/assets/armor/fs-61-dreadnought.png'),
  ('FS-11 Executioner', 'heavy', 'Fortified', '/api/assets/armor/fs-11-executioner.png'),
  ('CM-17 Butcher', 'heavy', 'Med-Kit', '/api/assets/armor/cm-17-butcher.png'),
  ('FS-55 Devastator', 'heavy', 'Fortified', '/api/assets/armor/fs-55-devastator.png'),
  ('CE-64 Grenadier', 'heavy', 'Engineering Kit', '/api/assets/armor/ce-64-grenadier.png'),
  ('CW-36 Winter Warrior', 'heavy', 'Servo-Assisted', '/api/assets/armor/cw-36-winter-warrior.png'),
  ('CE-101 Guerilla Gorilla', 'heavy', 'Engineering Kit', '/api/assets/armor/ce-101-guerilla-gorilla.png'),
  ('PH-202 Twigsnapper', 'heavy', 'Peak Physique', '/api/assets/armor/ph-202-twigsnapper.png'),
  ('I-44 Salamander', 'heavy', 'Inflammable', '/api/assets/armor/i-44-salamander.png'),
  ('AF-52 Lockdown', 'heavy', 'Advanced Filtration', '/api/assets/armor/af-52-lockdown.png'),
  ('SR-64 Cinderblock', 'heavy', 'Siege-Ready', '/api/assets/armor/sr-64-cinderblock.png'),
  ('SR-18 Roadblock', 'heavy', 'Siege-Ready', '/api/assets/armor/sr-18-roadblock.png'),
  ('GS-66 Lawmaker', 'heavy', 'Gunslinger', '/api/assets/armor/gs-66-lawmaker.png'),
  ('RE-824 Bearer of the Standard', 'heavy', 'Reinforced Epaulettes', '/api/assets/armor/re-824-bearer-of-the-standard.png'),
  ('BP-77 Grand Juror', 'heavy', 'Ballistic Padding', '/api/assets/armor/bp-77-grand-juror.png'),
  ('AD-49 Apollonian', 'heavy', 'Adreno-Defibrillator', '/api/assets/armor/ad-49-apollonian.png'),
  ('DS-42 Federation''s Blade', 'heavy', 'Desert Stormer', '/api/assets/armor/ds-42-federation-s-blade.png'),
  ('RS-40 Beast of Prey', 'heavy', 'Rock Solid', '/api/assets/armor/rs-40-beast-of-prey.png'),
  ('SA-8 Ram', 'heavy', 'Supplementary Adrenaline', '/api/assets/armor/sa-8-ram.png'),
  ('CPR-80 Bulwark', 'heavy', 'Concussive Padding', '/api/assets/armor/cpr-80-bulwark.png'),
  ('O-2 Heavy Operator', 'heavy', 'Oxygenator', '/api/assets/armor/o-2-heavy-operator.png');

-- ------------------------------------------------------------
-- Boosters
-- ------------------------------------------------------------
INSERT INTO boosters (name, image_url) VALUES
  ('Hellpod Space Optimization', '/api/assets/boosters/hellpod-space-optimization.png'),
  ('Vitality Enhancement', '/api/assets/boosters/vitality-enhancement.png'),
  ('UAV Recon Booster', '/api/assets/boosters/uav-recon-booster.png'),
  ('Stamina Enhancement', '/api/assets/boosters/stamina-enhancement.png'),
  ('Muscle Enhancement', '/api/assets/boosters/muscle-enhancement.png'),
  ('Increased Reinforcement Budget', '/api/assets/boosters/increased-reinforcement-budget.png'),
  ('Flexible Reinforcement Budget', '/api/assets/boosters/flexible-reinforcement-budget.png'),
  ('Localization Confusion', '/api/assets/boosters/localization-confusion.png'),
  ('Expert Extraction Pilot', '/api/assets/boosters/expert-extraction-pilot.png'),
  ('Motivational Shocks', '/api/assets/boosters/motivational-shocks.png'),
  ('Experimental Infusion', '/api/assets/boosters/experimental-infusion.png'),
  ('Firebomb Hellpods', '/api/assets/boosters/firebomb-hellpods.png'),
  ('Dead Sprint', '/api/assets/boosters/dead-sprint.png'),
  ('Armed Resupply Pods', '/api/assets/boosters/armed-resupply-pods.png'),
  ('Sample Extricator', '/api/assets/boosters/sample-extricator.png'),
  ('Sample Scanner', '/api/assets/boosters/sample-scanner.png'),
  ('Stun Pods', '/api/assets/boosters/stun-pods.png'),
  ('Concealed Insertion', '/api/assets/boosters/concealed-insertion.png');
